name: Build and Release AdGuard

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "14.4"
        required: true
        type: string
      adguard_version:
        description: "AdGuard Version"
        default: "1.0.0"
        required: true
        type: string
      decrypted_adguard_url:
        description: "Direct URL of the decrypted AdGuard IPA"
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Modify the bundle ID"
        default: "com.adguard.ios"
        required: true
        type: string
      app_name:
        description: "Modify the app name"
        default: "AdGuard"
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      upload_artifact:
        description: "Upload IPA as artifact"
        default: true
        required: false
        type: boolean
      create_release:
        description: "Create a draft release"
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build AdGuard
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.6
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          ref: 5bfdc3cb7133ec1cab43182115d902e2b57c9eac
          path: theos
          submodules: recursive

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichornlover/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare AdGuard iPA
        id: prepare_adguard
        run: |
          wget "$ADGUARD_URL" --no-verbose -O main/AdGuard.ipa
          cd ${{ github.workspace }}/main
          mv AdGuard.ipa AdGuard.zip
          unzip -q AdGuard.zip
          adguard_version=$(defaults read "$(pwd)/Payload/AdGuard.app/Info" CFBundleVersion)
          echo "==> AdGuard v$adguard_version downloaded!"
          sed -i '' "17s#.*#ADGUARD_VERSION = ${adguard_version}#g" Makefile
          echo "adguard_version=${adguard_version}" >> $GITHUB_OUTPUT

        env:
          THEOS: ${{ github.workspace }}/theos
          ADGUARD_URL: ${{ inputs.decrypted_adguard_url }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile                          # Modify the bundle ID
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile                        # Modify the app name
          sed -i '' "1s#.*#export TARGET = iphone:clang:${{ inputs.sdk_version }}:14.0#g" Makefile # Modify the SDK version
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/AdGuard.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

        env:
          THEOS: ${{ github.workspace }}/theos
          ADGUARD_VERSION: ${{ inputs.adguard_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.3
        env:
          ADGUARD_VERSION: ${{ inputs.adguard_version }}
          ADGUARD_VERSION: ${{ steps.prepare_adguard.outputs.adguard_version }}
        with:
          name: AdGuard_${{ env.ADGUARD_VERSION }}_${{ env.ADGUARD_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADGUARD_VERSION: ${{ inputs.adguard_version }}
          ADGUARD_VERSION: ${{ steps.prepare_adguard.outputs.adguard_version }}
        with:
          tag_name: v${{ env.ADGUARD_VERSION }}-${{ env.ADGUARD_VERSION }}-(${{ github.run_number }})
          name: v${{ env.ADGUARD_VERSION }}-${{ env.ADGUARD_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
